categories:
  - title: '🐛 Fixes'
    label: 'Bugfix'
  - title: '✨ Features'
    label: 'Feature'
  - title: '🧭 Changes'
    label: 'Enhancement'
  - title: '📦 Dependency updates'
    label: 'Renovate'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@'
exclude-contributors:
  - 'renovate'
  - 'renovate-bot'
template: |
  ## HoloPlots v
  $CHANGES
