main: com.empcraft.holoplots.Main
name: HoloPlots
version: "${version}"
api-version: "1.13"
authors: [Empire92, NotMyFault]
website: "https://www.spigotmc.org/resources/holoplots.4880/"
description: Holographic Plot signs
softdepend: [HolographicDisplays, PlotSquared, ProtocolLib]