main: com.empcraft.holoplots.Main
name: HoloPlots
version: 4.0.1
api-version: 1.13
authors: [Empire92, NotMyFault]
description: Holographic Plot signs
softdepend: [HolographicDisplays, PlotSquared, ProtocolLib]