[versions]
# Plugins
worldedit = "7.2.13"
holographicdisplays = "2.4.9"
decentholograms = "2.7.9"

# Gradle plugins
shadow = "7.1.2"
bukkityml = "0.5.2"

[libraries]
# Plugins
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
holographicdisplays = { group = "com.gmail.filoghost.holographicdisplays", name = "holographicdisplays-api", version.ref = "holographicdisplays" }
decentholograms = { group = "com.github.decentsoftware-eu", name = "decentholograms", version.ref = "decentholograms" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "bukkityml" }
