name: Announce release on discord
on:
  release:
    types: [published]
jobs:
  send_announcement:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: HoloPlots Release
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210 # ratchet:Ilshidur/action-discord@0.3.2
        with:
          args: |
            "<@&673138796690276352>"
            ""
            "<:holoplots:730750374117638195> **HoloPlots ${{ github.event.release.tag_name }} has been released!**"
            ""
            "Click here to view changelog: https://github.com/IntellectualSites/HoloPlots/releases/tag/${{ github.event.release.tag_name }}"
            ""
            "The download is available at:"
            "- Spigot: <https://www.spigotmc.org/resources/4880/>"
